#!/bin/sh

grep -q "^/usr/local/lib$" /etc/ld.so.conf 2>/dev/null || echo "/usr/local/lib" >> /etc/ld.so.conf
ldconfig

if ! [ -f /usr/local/etc/bind/rndc.key ] ; then
	rndc-confgen -a
	chmod 640 /usr/local/etc/bind/rndc.key
fi

chown -R root:bind /usr/local/etc/bind
chmod 750 /usr/local/etc/bind

